language: go

go:
  - 1.12.x
env:
  - GO111MODULE=on

script: 
  - go mod download
  - go get -u github.com/haya14busa/goverage
  - go test -v -race ./...
  - goverage -v -coverprofile=coverage.txt -covermode=atomic -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) 
